# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.0
      - image: circleci/redis:5.0.4
      - image: circleci/mongodb:4.2.7
    working_directory: ~/repo
    steps:
      - checkout
      # BUILD UP
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install

      # run tests!
      - run: yarn tslint
      - run: yarn test

      # save caches
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
